behaviors:
  Launcher:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      memory_size: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 120
    summary_freq: 10000
environment_parameters:
  rewardRadius:
    curriculum:
      - name: Lesson0 
        completion_criteria: 
          measure: reward
          behavior: Launcher
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
          require_reset: true
        value: 100
      - name: Lesson1 
        completion_criteria: 
          measure: reward
          behavior: Launcher
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3.0
          require_reset: true
        value: 75
      - name: Lesson2 
        completion_criteria: 
          measure: reward
          behavior: Launcher
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6.0
          require_reset: true
        value: 50
      - name: Lesson3 
        value: 25
